extensions:
  health_check: {}
receivers:
  docker_stats:
    #endpoint: unix:///var/run/docker.sock
    #endpoint: http://example.com/
    collection_interval: 15s
    container_labels_to_metric_labels:
      my.container.label: valmi-activation
      #my.other.container.label: my-other-metric-label
    env_vars_to_metric_labels:
      APP_BACKEND : app-backend-metric-label
      #MY_OTHER_ENVIRONMENT_VARIABLE: my-other-metric-label
    excluded_images:
      - undesired-container
      - /.*undesired.*/
      - another-*-container
    metrics:
      container.cpu.usage.percpu:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: false
  otlp:
    protocols:
      grpc:
  fluentforward:
    endpoint: 0.0.0.0:8006
processors:
  resourcedetection:
    detectors: [env, system]
  batch:
    timeout: 10s
  # Will convert all monotonic, cumulative sums to monotonic, delta sums
  cumulativetodelta:
  transform:
    trace_statements:
      - context: span
        statements:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)
    log_statements:
      - context: log
        statements:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)
exporters:
  logging:
    verbosity: $LOG_EXPORTER_LOG_VERBOSITY
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": $NEW_RELIC_API_KEY
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, docker_stats]
      processors: [cumulativetodelta, batch, resourcedetection]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp, fluentforward]
      processors: [transform, batch]
      exporters: [logging, otlp]